# [作業目標]

1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```

2. 請對一個 5x5 的隨機矩陣作正規化的操作。

3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


# 作業 

### 1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```



In [ ]:
#a.sum()是numpy的陣列底下的函式；np.sum(a)則是numpy底下的函式
#sum(a) 則是 python的函式，在np以外的地方也可以使用

'\nYour Code\n'

### 2. 請對一個 5x5 的隨機矩陣作正規化的操作。


In [1]:
# 記得先 Import 正確的套件

import numpy as np

In [2]:
A = np.random.random((5, 5))

'''
Your Code
'''

'\nYour Code\n'

In [7]:
print(A)

A = (A - A.min()) / (A.max() - A.min())
A

[[0.8802826  0.84508809 0.99471708 0.81226862 0.34198125]
 [0.31025741 0.99748811 0.11968921 0.62269714 0.29326581]
 [0.13705521 0.0631651  0.38192782 0.45086138 0.94773516]
 [0.32414761 0.96057922 0.44911454 0.43660074 0.76921043]
 [0.4830934  0.70572395 0.18214455 0.40061941 0.84020162]]


array([[0.87455569, 0.83688722, 0.99703418, 0.80176075, 0.29841516],
       [0.26446133, 1.        , 0.0604974 , 0.59886359, 0.24627533],
       [0.07908412, 0.        , 0.34116972, 0.41494888, 0.94674973],
       [0.27932792, 0.96049665, 0.41307924, 0.3996858 , 0.75567584],
       [0.44944661, 0.68772666, 0.12734295, 0.36117521, 0.83165727]])

### 3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


In [ ]:
'''
Your Code
'''

[ 0.29347583  0.59303277 -1.          0.38043546  0.63265939  0.32472618
  0.11340241  0.68136955  0.89905432  0.74769935]


In [14]:
a = np.random.random(10)
a

array([0.23280383, 0.03740351, 0.26011334, 0.85064883, 0.51379427,
       0.5521867 , 0.371787  , 0.06906418, 0.81238376, 0.1553882 ])

In [15]:
a = (a*100).round()
a

array([23.,  4., 26., 85., 51., 55., 37.,  7., 81., 16.])

In [16]:
a[a.argmax()] = -1
a

array([23.,  4., 26., -1., 51., 55., 37.,  7., 81., 16.])