# [作業目標]

1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```

2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。
3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。

# 作業 

### 1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```


In [1]:
print('zeros會產生零，empty則會產生很小的數。使用empty可以不用給定起始值，有時候操作上比較方便')

zeros會產生零，empty則會產生很小的數


### 2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。


In [4]:
# 記得先 Import 正確的套件

import numpy as np
from numpy.random import default_rng
rng = default_rng()

In [11]:
# 參考解答

a = np.random.rand(2, 3)
print(a)

a = a*100
a.round()

[[0.07862743 0.00248693 0.03760163]
 [0.69395561 0.02909192 0.99557171]]


array([[  8.,   0.,   4.],
       [ 69.,   3., 100.]])

### 3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。


In [16]:
m = 20
n = 40

a = np.random.rand(2,3) * (n-m) #先把range平移調大
b = a

print(a - b%1 + m) #把a扣掉小數點，然後再平移一次

[[31. 30. 31.]
 [23. 29. 32.]]
