# [作業目標]

1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。
2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？



# 作業 

### 1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。



In [1]:
# 記得先 Import 正確的套件

import numpy as np

In [34]:
a = np.arange(1, 12)

print(a)

a[(a>2) & (a<7)] *= -1
a

[ 1  2  3  4  5  6  7  8  9 10 11]


array([ 1,  2, -3, -4, -5, -6,  7,  8,  9, 10, 11])

### 2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？



In [39]:
A = np.random.rand(3, 6)

print(A)

print(len(A[A > 0.5]))
print(A[A > 0.5].size)

[[0.98142811 0.66961356 0.61562582 0.71039892 0.46865085 0.17361919]
 [0.28288313 0.70808296 0.29638734 0.43271526 0.58423319 0.71975003]
 [0.72483125 0.61679218 0.95634066 0.8013419  0.86404619 0.68883832]]
13
13
